#!/bin/bash
#
#Script para converter imagens de .jpg para .png
#Autor: Rodrigo Sousa
#
echo "inicializando"

cd imagens-livros

for imagem in *.jpg
do
	echo $imagem
	img_sem-ext=(ls $imagem | awk -F. '{print $1}')
	convert $imagem $img_sem_ext.png
done

echo "finalizando"

#alterado por ryan!

cd..
